-- V20260814__outbound.sql
-- 销售出库单（对齐出库单填写页）

USE cailu_bom;

CREATE TABLE IF NOT EXISTS erp_outbound_order (
    id              BIGINT         NOT NULL PRIMARY KEY,
    bill_no         VARCHAR(64)    NOT NULL COMMENT '系统单号',
    custom_no       VARCHAR(64)    NULL COMMENT '自编号',
    bill_date       DATE           NOT NULL COMMENT '开单日期',
    outbound_type   VARCHAR(32)    NOT NULL COMMENT '出库类型',
    order_no        VARCHAR(64)    NULL COMMENT '订货单号',
    order_custom_no VARCHAR(64)    NULL COMMENT '订货自编号',
    order_date      DATE           NULL COMMENT '订货日期',
    order_type      VARCHAR(32)    NULL COMMENT '订单类型',
    customer_code   VARCHAR(64)    NOT NULL COMMENT '客户编码',
    customer_name   VARCHAR(128)   NOT NULL COMMENT '客户名称',
    contact         VARCHAR(64)    NULL,
    mobile          VARCHAR(32)    NULL,
    community       VARCHAR(128)   NULL COMMENT '所属小区',
    address         VARCHAR(255)   NOT NULL COMMENT '送货地址',
    channel         VARCHAR(64)    NULL COMMENT '销售渠道',
    customer_level  VARCHAR(32)    NULL,
    sales_dept      VARCHAR(64)    NOT NULL COMMENT '部门',
    salesperson     VARCHAR(64)    NULL COMMENT '业务员',
    guide           VARCHAR(64)    NULL COMMENT '导购员',
    designer        VARCHAR(64)    NULL COMMENT '驻场设计师',
    design_method   VARCHAR(64)    NULL,
    ship_from       VARCHAR(64)    NULL COMMENT '发货地点',
    delivery_method VARCHAR(64)    NULL COMMENT '送货方式',
    package_product VARCHAR(128)   NULL COMMENT '套餐商品',
    handler         VARCHAR(64)    NULL COMMENT '经手人',
    inner_remark    VARCHAR(255)   NULL,
    outer_remark    VARCHAR(255)   NULL,
    status          VARCHAR(32)    NOT NULL DEFAULT 'draft' COMMENT 'draft/effective',
    total_amount    DECIMAL(18, 4) NOT NULL DEFAULT 0,
    total_qty       DECIMAL(18, 4) NOT NULL DEFAULT 0,
    total_boxes     DECIMAL(18, 4) NOT NULL DEFAULT 0,
    total_sqm       DECIMAL(18, 4) NOT NULL DEFAULT 0,
    total_weight    DECIMAL(18, 4) NOT NULL DEFAULT 0,
    created_at      DATETIME       NULL,
    updated_at      DATETIME       NULL,
    created_by      BIGINT         NULL,
    updated_by      BIGINT         NULL,
    deleted         TINYINT        NOT NULL DEFAULT 0,
    UNIQUE KEY uk_erp_outbound_bill (bill_no),
    KEY idx_erp_outbound_customer (customer_code),
    KEY idx_erp_outbound_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS erp_outbound_order_item (
    id              BIGINT         NOT NULL PRIMARY KEY,
    order_id        BIGINT         NOT NULL,
    line_no         INT            NOT NULL DEFAULT 1,
    position        VARCHAR(64)    NULL COMMENT '使用位置',
    product_id      BIGINT         NULL,
    sku             VARCHAR(128)   NOT NULL,
    product_name    VARCHAR(128)   NULL,
    brand           VARCHAR(64)    NULL,
    spec            VARCHAR(128)   NULL,
    grade           VARCHAR(32)    NULL,
    batch_no        VARCHAR(64)    NULL COMMENT '批次/色号',
    sets_qty        DECIMAL(18, 4) NOT NULL DEFAULT 0,
    boxes           DECIMAL(18, 4) NOT NULL DEFAULT 0,
    pieces          DECIMAL(18, 4) NOT NULL DEFAULT 0,
    qty             DECIMAL(18, 4) NOT NULL,
    unit            VARCHAR(16)    NULL,
    std_price       DECIMAL(18, 4) NOT NULL DEFAULT 0,
    discount        DECIMAL(18, 4) NOT NULL DEFAULT 0,
    price           DECIMAL(18, 4) NOT NULL DEFAULT 0,
    amount          DECIMAL(18, 4) NOT NULL DEFAULT 0,
    warehouse_id    BIGINT         NULL,
    warehouse_code  VARCHAR(64)    NULL,
    warehouse_name  VARCHAR(128)   NULL,
    bin_name        VARCHAR(64)    NULL,
    fee_type        VARCHAR(64)    NULL COMMENT '费用类别',
    occupy          TINYINT        NOT NULL DEFAULT 0,
    count_perf      TINYINT        NOT NULL DEFAULT 1,
    KEY idx_erp_outbound_item_order (order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
